package cn.cs.Board.dao.model;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mb_user.id
	 * @mbg.generated  Tue Feb 26 14:43:55 CST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mb_user.login_name
	 * @mbg.generated  Tue Feb 26 14:43:55 CST 2019
	 */
	private String loginName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mb_user.username
	 * @mbg.generated  Tue Feb 26 14:43:55 CST 2019
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mb_user.password
	 * @mbg.generated  Tue Feb 26 14:43:55 CST 2019
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mb_user.description
	 * @mbg.generated  Tue Feb 26 14:43:55 CST 2019
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mb_user.profile_pic
	 * @mbg.generated  Tue Feb 26 14:43:55 CST 2019
	 */
	private String profilePic;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mb_user.id
	 * @return  the value of mb_user.id
	 * @mbg.generated  Tue Feb 26 14:43:55 CST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mb_user.id
	 * @param id  the value for mb_user.id
	 * @mbg.generated  Tue Feb 26 14:43:55 CST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mb_user.login_name
	 * @return  the value of mb_user.login_name
	 * @mbg.generated  Tue Feb 26 14:43:55 CST 2019
	 */
	public String getLoginName() {
		return loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mb_user.login_name
	 * @param loginName  the value for mb_user.login_name
	 * @mbg.generated  Tue Feb 26 14:43:55 CST 2019
	 */
	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mb_user.username
	 * @return  the value of mb_user.username
	 * @mbg.generated  Tue Feb 26 14:43:55 CST 2019
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mb_user.username
	 * @param username  the value for mb_user.username
	 * @mbg.generated  Tue Feb 26 14:43:55 CST 2019
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mb_user.password
	 * @return  the value of mb_user.password
	 * @mbg.generated  Tue Feb 26 14:43:55 CST 2019
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mb_user.password
	 * @param password  the value for mb_user.password
	 * @mbg.generated  Tue Feb 26 14:43:55 CST 2019
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mb_user.description
	 * @return  the value of mb_user.description
	 * @mbg.generated  Tue Feb 26 14:43:55 CST 2019
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mb_user.description
	 * @param description  the value for mb_user.description
	 * @mbg.generated  Tue Feb 26 14:43:55 CST 2019
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mb_user.profile_pic
	 * @return  the value of mb_user.profile_pic
	 * @mbg.generated  Tue Feb 26 14:43:55 CST 2019
	 */
	public String getProfilePic() {
		return profilePic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mb_user.profile_pic
	 * @param profilePic  the value for mb_user.profile_pic
	 * @mbg.generated  Tue Feb 26 14:43:55 CST 2019
	 */
	public void setProfilePic(String profilePic) {
		this.profilePic = profilePic;
	}
}