package cn.cs.Board.dao.mapper;

import cn.cs.Board.dao.model.Msg;
import cn.cs.Board.dao.model.MsgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MsgMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mb_msg
	 * @mbg.generated  Tue Feb 26 14:43:55 CST 2019
	 */
	long countByExample(MsgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mb_msg
	 * @mbg.generated  Tue Feb 26 14:43:55 CST 2019
	 */
	int deleteByExample(MsgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mb_msg
	 * @mbg.generated  Tue Feb 26 14:43:55 CST 2019
	 */
	int insert(Msg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mb_msg
	 * @mbg.generated  Tue Feb 26 14:43:55 CST 2019
	 */
	int insertSelective(Msg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mb_msg
	 * @mbg.generated  Tue Feb 26 14:43:55 CST 2019
	 */
	List<Msg> selectByExample(MsgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mb_msg
	 * @mbg.generated  Tue Feb 26 14:43:55 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Msg record, @Param("example") MsgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mb_msg
	 * @mbg.generated  Tue Feb 26 14:43:55 CST 2019
	 */
	int updateByExample(@Param("record") Msg record, @Param("example") MsgExample example);
}